if (!process.env.NEXT_PUBLIC_COIN_API_URL) {
  throw new Error('NEXT_PUBLIC_COIN_API_URL is not set')
}

export const COIN_API_URL = process.env.NEXT_PUBLIC_COIN_API_URL

if (!process.env.NEXT_PUBLIC_VEWORLD_INDEXER_MAINNET_URL) {
  throw new Error('NEXT_PUBLIC_VEWORLD_INDEXER_MAINNET_URL is not set')
}

export const VEWORLD_INDEXER_MAINNET_URL = process.env.NEXT_PUBLIC_VEWORLD_INDEXER_MAINNET_URL

if (!process.env.NEXT_PUBLIC_VEWORLD_INDEXER_TESTNET_URL) {
  throw new Error('NEXT_PUBLIC_VEWORLD_INDEXER_TESTNET_URL is not set')
}

export const VEWORLD_INDEXER_TESTNET_URL = process.env.NEXT_PUBLIC_VEWORLD_INDEXER_TESTNET_URL
