'use client'

import { Box, Flex, Skeleton, Text } from '@chakra-ui/react'
import { useTranslation } from 'react-i18next'
import { formatEther } from 'viem'
import { LuLayers, LuShield, LuZap } from 'react-icons/lu'
import { NetworkName } from '@/lib/constants/network'
import { useSettingsStore } from '@/lib/stores/settings'
import { useTotalVetStaked } from '@/services/veworld-indexer/total-vet-staked'
import { useFormatNumber } from '@/hooks/useFormatting'

// VeChainThor has a fixed max supply of 86.71B VET — no inflation, no
// minting beyond the genesis allocation. Match the design's `cluster` strip
// which hard-codes this against the live staked figure.
const MAX_SUPPLY_VET = 86_712_634_466
const STARGATE_DELEGATOR_SHARE_OF_GENERATION = 0.4

/**
 * Three-tile strip beneath the stat tiles: Circulating Supply (with a
 * progress bar vs the fixed max), VET locked in StarGate, and a passive
 * VTHO-generation rate. Renders only on mainnet/testnet — solo doesn't
 * meaningfully model these numbers.
 */
export const ClusterStrip = () => {
  const { t } = useTranslation()
  const formatNumber = useFormatNumber()
  const { activeNetwork } = useSettingsStore()
  const isSolo = activeNetwork.name === NetworkName.SOLO
  const { data: stakedData, isLoading: stakedLoading } = useTotalVetStaked()

  if (isSolo) return null

  const totalStakedVet = stakedData?.total ? Number(formatEther(stakedData.total)) : 0
  const stakedPctOfSupply = (totalStakedVet / MAX_SUPPLY_VET) * 100
  // VTHO is generated by all VET holders at 0.000432 VTHO/VET/day. Stargate
  // share is the slice users see — a useful 24h ballpark of "what's flowing
  // through delegators" for the home page.
  const stargate24hVtho = totalStakedVet * 0.000432 * STARGATE_DELEGATOR_SHARE_OF_GENERATION

  return (
    <Flex
      borderWidth="1px"
      borderColor="border-primary"
      bg="row-even-bg-primary"
      rounded="2xl"
      overflow="hidden"
      direction={{ base: 'column', md: 'row' }}
    >
      <ClusterCell
        icon={<LuShield size={14} />}
        label={t('Circulating supply')}
        value={
          <Flex alignItems="baseline" gap="1.5">
            <Text textStyle="displayXs">
              {formatNumber(MAX_SUPPLY_VET / 1_000_000_000, { maximumFractionDigits: 2 })}
            </Text>
            <Text textStyle="bodyS" color="text-secondary">
              {t('B VET (max supply)')}
            </Text>
          </Flex>
        }
        footer={
          <Box mt="3">
            <Box height="6px" rounded="full" bg="bg-primary" overflow="hidden">
              <Box
                height="100%"
                rounded="full"
                bgGradient="to-r"
                gradientFrom="accent-primary"
                gradientTo="accent-secondary"
                width="100%"
              />
            </Box>
            <Flex justifyContent="space-between" mt="2" textStyle="bodyXs" color="text-secondary">
              <Text>{t('Fixed max — no inflation')}</Text>
              <Text>{formatNumber(MAX_SUPPLY_VET, { maximumFractionDigits: 0 })} VET</Text>
            </Flex>
          </Box>
        }
      />
      <ClusterCell
        icon={<LuLayers size={14} />}
        label={t('VET staked via StarGate')}
        value={
          stakedLoading ? (
            <Skeleton height="28px" width="120px" />
          ) : (
            <Flex alignItems="baseline" gap="1.5">
              <Text textStyle="displayXs">
                {formatNumber(totalStakedVet / 1_000_000_000, { maximumFractionDigits: 2 })}
              </Text>
              <Text textStyle="bodyS" color="text-secondary">
                {t('B VET')}
              </Text>
            </Flex>
          )
        }
        footer={
          <Text textStyle="bodyXs" color="accent-primary" mt="2">
            {stakedLoading ? '' : `${stakedPctOfSupply.toFixed(2)}% ${t('of max supply')}`}
          </Text>
        }
      />
      <ClusterCell
        icon={<LuZap size={14} />}
        label={t('VTHO generated · 24h')}
        value={
          stakedLoading ? (
            <Skeleton height="28px" width="120px" />
          ) : (
            <Flex alignItems="baseline" gap="1.5">
              <Text textStyle="displayXs">
                {formatNumber(stargate24hVtho / 1_000_000, { maximumFractionDigits: 2 })}
              </Text>
              <Text textStyle="bodyS" color="text-secondary">
                {t('M VTHO from StarGate')}
              </Text>
            </Flex>
          )
        }
        footer={
          <Text textStyle="bodyXs" color="text-secondary" mt="2">
            {t('0.000432 VTHO / VET / day')}
          </Text>
        }
      />
    </Flex>
  )
}

const ClusterCell = ({
  icon,
  label,
  value,
  footer,
}: {
  icon: React.ReactNode
  label: string
  value: React.ReactNode
  footer?: React.ReactNode
}) => {
  return (
    <Box
      flex="1"
      px="5"
      py="4"
      borderRightWidth={{ base: 0, md: '1px' }}
      borderBottomWidth={{ base: '1px', md: 0 }}
      borderColor="border-primary"
      _last={{ borderRightWidth: 0, borderBottomWidth: 0 }}
    >
      <Flex alignItems="center" gap="2" color="text-secondary" mb="2">
        <Box color="accent-primary">{icon}</Box>
        <Text textStyle="bodyXs">{label}</Text>
      </Flex>
      {value}
      {footer}
    </Box>
  )
}
