name: Codebase Versioning

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  semantic-versioning:
    uses: vechain/github-actions-public/.github/workflows/semantic-versioning.yaml@c8645e5723b09ce657b865f78924b87a357df036 # v.2.3.1
    secrets:
      DEPLOY_KEY: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}
