name: Deploy static files
on:
    push:
        branches: [master]
        paths: ['src/**', '.github/workflows/deploy-static-files.yml']
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: dev
        env:
            AWS_DEFAULT_REGION: eu-west-1
            BUCKET_NAME: ${{ vars.BUCKET_NAME }}
            DISTRIBUTION_ID: ${{ vars.CLOUDFRONT_ID }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 'v22.12.0'
                  cache: 'yarn'
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                aws-region: eu-west-1
                role-to-assume: ${{ secrets.AWS_ACCESS_ROLE }}

            - name: Install dependencies
              run: yarn --immutable
            
            - name: Build 
              run: yarn  build

            - name: Deploy S3
              run: |
                  aws s3 sync dist s3://$BUCKET_NAME --delete
            - name: Cloudfront Invalidation
              run: |
                  AWS_MAX_ATTEMPTS=10 aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/' '/*'
