name: Validate PR Label
on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]
  workflow_dispatch:

jobs:
  validate:
    uses: vechain/github-actions-public/.github/workflows/validate-pr-label.yaml@c8645e5723b09ce657b865f78924b87a357df036 # v.2.3.1
    with:
      FAIL_IF_MISSING_LABEL: true
